### PR TITLE
Bump to bref/build-php-XX:1.1.4

### PR DESCRIPTION
**Pull request by Nyholm**
This is related to https://github.com/brefphp/bref/pull/830

Maybe @shouze could help me understand why there is a build failure?

### CODE REVIEW

**Comment by Nyholm** [comment]
@cisox, we changed base image to one that is provided by AWS. It complains on the imap image, at the following line `RUN amazon-linux-extras install epel -y`

Do we need `amazon-linux-extras`, can we rewrite that line?

**Comment by Nyholm** [comment]
@valentijnscholten, maybe you can help with the Cassandra extension?

**Comment by shouze** [comment]
> @valentijnscholten, maybe you can help with the Cassandra extension?

@Nyholm to me, as the new amazon linux 2 layers & docker image aloready contains `/usr/lib64/libuv.so.1` file we can trash every line of the Dockerfile related to the download and copy of the `libuv.so.1` shared library.

**Comment by shouze** [comment]
> @cisox, we changed base image to one that is provided by AWS. It complains on the imap image, at the following line `RUN amazon-linux-extras install epel -y`
> 
> Do we need `amazon-linux-extras`, can we rewrite that line?

@Nyholm  I've produced a Dockerfile that seems to work.
@cisox can you confirm this looks good to you?
```Dockefile
ARG PHP_VERSION
FROM bref/build-php-$PHP_VERSION:1.1.4 AS ext

RUN LD_LIBRARY_PATH=/lib:/lib64 yum -y install amazon-linux-extras
RUN LD_LIBRARY_PATH=/lib:/lib64 amazon-linux-extras install epel -y
RUN LD_LIBRARY_PATH=/lib:/lib64 yum -y install uw-imap-devel krb5-devel openssl-devel libc-client-devel

WORKDIR ${PHP_BUILD_DIR}/ext/imap
RUN phpize
RUN ./configure --with-imap --with-kerberos --with-imap-ssl --with-libdir=lib64 --disable-static
RUN make -j `nproc` && make install

RUN cp `php-config --extension-dir`/imap.so /tmp/imap.so
RUN echo 'extension=/opt/bref-extra/imap.so' > /tmp/ext.ini

# Build the final image with just the files we need
FROM scratch

# Copy things we installed to the final image
COPY --from=ext /usr/lib64/libc-client.so.2007 /opt/bref/lib64/libc-client.so.2007
COPY --from=ext /usr/lib64/libpam.so.0 /opt/bref/lib64/libpam.so.0
COPY --from=ext /usr/lib64/libaudit.so.1 /opt/bref/lib64/libaudit.so.1
COPY --from=ext /usr/lib64/libcap-ng.so.0 /opt/bref/lib64/libcap-ng.so.0
COPY --from=ext /tmp/imap.so /opt/bref-extra/imap.so
COPY --from=ext /tmp/ext.ini /opt/bref/etc/php/conf.d/ext-imap.ini
```

**Comment by Nyholm** [comment]
Thank you. It seams to be fine now. I'll wait for CI to confirm

**Pull request merged**
