### PR TITLE
 imagick support for PHP 8.1

### PR DESCRIPTION
**Pull request by aran112000**

### CODE REVIEW

**Comment by Nyholm** [comment]
Hm.. The CI is failing.

**Comment by christophe-mailfert** [comment]
Hi there, any news or update for this pull request ?

**Comment by Nyholm** [comment]
I would be happy to merge, but the CI must be green.

**Comment by peldax** [comment]
This one only adds 81 to the configuration, but there is some tinkering in Dockerfile needed. I created another PR and I am trying to make it work.

**Comment by Nyholm** [comment]
Fixed by #309

**Pull request closed without merging**
