### PR TITLE
Add imagick with webp support and binding to newer versions of ImageMagick

### PR DESCRIPTION
**Pull request by RikudouSage**
I tested it with php 7.2, 7.3 and 7.4.

What I tested:

- image can be outputted in the webp format
- the method `compositeImageGravity()` exists

### CODE REVIEW

**Comment by mnapoli** [comment]
FYI the extension already exists in Bref. More here: https://github.com/brefphp/bref/issues/630

**Comment by RikudouSage** [comment]
Yeah, but it uses ImageMagick from repo which is kinda outdated.

**Comment by mnapoli** [comment]
By the way how heavy is this layer?

If it is (with the new system library included), maybe it would make sense to deprecate (and eventually remove) the one bundled with Bref.

If not, having this extension here would duplicate what's in the main layer, it wouldn't make sense.

**Comment by RikudouSage** [comment]
Around 6,800 KiB.

**Comment by RikudouSage** [comment]
Around 14 MiB if you also add HEIC/HEIF support.

**Comment by RikudouSage** [comment]
Had to change the URL to a GitHub one since imagemagick.org deletes older builds once a new one is published.

**Comment by mnapoli** [comment]
Oh wow, this is huge indeed. Probably best to move the extension in here then.

I have opened https://github.com/brefphp/bref/issues/636 to deprecate the built-in imagick extension.

**Pull request merged**
