### PR TITLE
Add layer for Datadog extension

### LINKED ISSUE #35: Datadog extension
Create a layer extension with Datadog APM for PHP.

### PR DESCRIPTION
**Pull request by ramsey**
This PR adds a layer containing the Datadog Agent and ddtrace extension, following the approach @deleugpn describes at https://blog.deleu.dev/datadog-aws-lambda-php/

I have built the layers and tested this with my own serverless application, and it properly sends logging and tracing information to Datadog.

Here's an example `serverless.yml` configuration for this layer:

```yaml
service: my-service

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
    env: ${env:MY_DEPLOYMENT_ENVIRONMENT}
    logLevel: ${env:DD_LOG_LEVEL, 'warn'}
    service: ${self:service}
    version: ${env:MY_VERSION}

plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions

provider:
  name: aws
  region: us-east-1
  runtime: provided.al2
  layers:
    - ${bref:layer.php-82}
    - ${bref-extra:datadog-php-82}
  deploymentMethod: direct
  environment:
    DD_API_KEY: ${self:custom.datadog.apiKey}
    DD_ENV: ${self:custom.datadog.env}
    DD_LOG_LEVEL: ${self:custom.datadog.logLevel}
    DD_SERVICE: ${self:custom.datadog.service}
    DD_TRACE_CLI_ENABLED: 1
    DD_VERSION: ${self:custom.datadog.version}

functions:
  sayHello:
    handler: ./src/sayHello.php
```

This closes #35, when accepted.

### CODE REVIEW

**Comment by wolflingorg** [comment]
Hey Ramsey, team

Re that article you are referring (https://blog.deleu.dev/datadog-aws-lambda-php/)
We also followed it to integrate DD into Bref Laravel lambda.

After integration, found lots of notices in CloudWatch like:
`NOTICE: PHP message: Error loading deferred integration 'DDTrace\Integrations\Predis\PredisIntegration' from DDTrace\Integrations\load_deferred_integration`
(*the same is for eloquent, pdo etc)

Right now - discussing that issue with DD support.

I wonder - does anyone have the same notices?

**Comment by ramsey** [comment]
@wolflingorg, the blog post doesn't mention copying over the integrations, which is sounds like you're trying to use. In order to use those, you need a line like this:

```
COPY --from=ext /opt/datadog/ /opt/datadog
```

You also need to make sure your Datadog INI settings are configured to link properly to the integrations code in `/opt/datadog`, which the default `98-ddtrace.ini` file includes.

This is all handled in this pull request. If you'd like to give it a try and report back, that would help a lot. Thanks!

**Comment by wolflingorg** [comment]
Hey,

Thanks for sharing an example & comments. You're right, looks like we missed something. After applying what you suggested, all looks good.

Thanks a lot

**Comment by ramsey** [comment]
> The only thing I noticed: you installed DD without an "--enable-profiling" flag (and also commented out profiling in the .ini file)... Is there any reason why?

My understanding is that profiling is still in beta. The extension `.so` file is still available in the layer, so if you want to enable it, you can follow the instructions for Bref to create custom INI configuration and enable it.

**Comment by mnapoli** [comment]
Hi, to provide some update here: on my end it looks good, but unfortunately we released Bref v2 which impacts the build here. I'm afraid you would have to rebase (you can look at how Dockerfiles look in the repo now to get some examples)

**Comment by fbnfgc** [comment]
Hi, we are looking forward to use datadog. We're still using bref v1 but we are planning to migrate to v2 in a near future. Are you still working on this @ramsey? Do you need some help?

**Comment by ramsey** [comment]
I went in a different direction, for now. Soon, I’ll open a new pull request with the changes I made.

**Pull request closed without merging**
