### PR TITLE
Prepare release for Bref 1.0

### PR DESCRIPTION
**Pull request by Nyholm**
Hm.. Only AMQP changed. We didn't get PHP8 here.. 

FYI @shouze

### CODE REVIEW

**Comment by shouze** [comment]
Well, this sounds weird. BTW I've also opened https://github.com/brefphp/extra-php-extensions/pull/108.
Will investigate on the reason.

**Comment by Nyholm** [comment]
This is super strange.. After the "build" step, we only have two layers: https://github.com/brefphp/extra-php-extensions/pull/106/checks?check_run_id=1457629075#step:6:10

**Comment by Nyholm** [comment]
Ah, I found the bug =)

**Comment by shouze** [comment]
Here we go, réajuster in time for php80 release

**Pull request merged**
