### PR TITLE
Imagick for PHP 8.1

### PR DESCRIPTION
**Pull request by peldax**
Hi,
This PR supersedes https://github.com/brefphp/extra-php-extensions/pull/289.
I enabled PHP 8.1 for Imagick and tried to fix failing CI.

I used Imagick version 3.7 for PHP 8.1 - I extended the if expression which chooses the right version (it was introduced in #143 ).
Hopefully it builds... :)

### CODE REVIEW

**Comment by peldax** [comment]
@Nyholm Hello, I got the CI working for Imagick with PHP 8.1. Imagick version used is 3.7 (latest).

**Comment by GrahamCampbell** [comment]
Does 3.7.0 not work on PHP 8.0 and 7.4, too?

**Comment by peldax** [comment]
I am not sure, I just followed existing pattern.

**Comment by GrahamCampbell** [comment]
The existing pattern was only there to temporarily upgrade to an unreleased version to get PHP 8.0 to work.

**Comment by peldax** [comment]
Ok, lets try 3.7 for every PHP version. Lets see if it builds.

**Review by Nyholm — APPROVED** [review]
Wohoo. Thank you!

**Pull request merged**
