### PR TITLE
Updated test for writing text to images using imagick 

### LINKED ISSUE #155: Bug in imagick when rendering text on a page - cannot write text on image (freetype missing?)
In trying to write text on an image using Imagick, the following error comes up when using the imagick layer;

php-fpm: DelegateLibrarySupportNotBuiltIn '/var/task/public/fonts/Arial.ttf' (Freetype) @ warning/annotate.c/RenderFreetype/1844.
CRITICAL - request()] Uncaught PHP Exception ImagickException: "Failed to query the font metrics" at /var/task/src/GeoJSON2Image.php line 484

The line of code is the following;
$canvas = new Imagick();
....
$draw = new ImagickDraw();
$label = 'my label';
...
$metrics = $canvas->queryFontMetrics($draw, $label);

It's basically to add annotations (text, explaining parts of an image).
Any help would be appreciated -- i'm a little stuck with what to do, and it looks like there's some vague mention of it elsewhere, with a reference to freetype not being included when compiling imagick (when imagick was used in other projects (outside of Bref))

### PR DESCRIPTION
**Pull request by victormacko**
As requested in issue #155 

This PR will fix #155

### CODE REVIEW

**Comment by Nyholm** [comment]
@victormacko Could you help me out here?

The CI seams to be green but locally I get a segfault. 

Could you checkout this branch and run:

```
 layer=imagick php_versions=74 make test
 ```

I get the following output locally. Do you get something else?
```
###############################################
###############################################
### Testing layers/imagick PHP74
###
Sending build context to Docker daemon  2.048kB
Step 1/5 : ARG PHP_VERSION
Step 2/5 : ARG TARGET_IMAGE
Step 3/5 : FROM bref/$TARGET_IMAGE AS ext
 ---> c4f941d97370
Step 4/5 : FROM bref/php-$PHP_VERSION:1.0.0
 ---> d93bc005afcf
Step 5/5 : COPY --from=ext /opt /opt
 ---> Using cache
 ---> 20d7af283a5c
Successfully built 20d7af283a5c
Successfully tagged bref/test-layers/imagick-74:latest
make: *** [test] Error 139

```
(Error 139 means segfault).

**Comment by victormacko** [comment]
Strangely, I got this when I ran it the first time;

Step 5/5 : COPY --from=ext /opt /opt
 ---> Using cache
 ---> 690bf8e28464
Successfully built 690bf8e28464
Successfully tagged bref/test-layers/imagick-74:latest
 - Test passed

... then I pulled in the latest commit (styling), and then got this;

Step 4/5 : FROM bref/php-$PHP_VERSION:1.0.0
 ---> d93bc005afcf
Step 5/5 : COPY --from=ext /opt /opt
 ---> Using cache
 ---> 690bf8e28464
Successfully built 690bf8e28464
Successfully tagged bref/test-layers/imagick-74:latest
make: *** [test] Error 139

I wonder if there's some cached/tmp data which it's using which 'make clean' doesn't get rid of?

**Comment by Nyholm** [comment]
> UPDATE @Nyholm ; On restarting docker, I built the layer again, which passed ... a subsequent build failed with that seg-fault.

Hm... I cannot reproduce that behavior.. Restarting docker did nothing for me.


> I wonder if there's some cached/tmp data which it's using which 'make clean' doesn't get rid of?

I've built it some a docker image and a test image. Running the script passing without and segfault. When I retry building the docker image (all reads from cache) and the test image, I'll get a segfault... 

Hm.. Im giving up for now.

**Comment by victormacko** [comment]
I've been digging into this a lil bit @Nyholm - I think the seg-fault (error 139) is happening inside docker when it removes the volumes containing temp files -- there's some references here to it where temp files weren't getting cleaned up properly; https://github.com/ImageMagick/ImageMagick/issues/395

Adding the command i've committed removes the files manually within the docker-image before docker removes it - 

If I add in the command there it seems to do the job - hopefully it helps (not entirely sure if you'd want to keep this in there though .. my docker skills aren't amazing so i'm sure there's a better way that I've just missed).

**Comment by Nyholm** [comment]
Awesome. Thank you. 

I've tried a bit to remove the temp files in PHP.. But there is none starting with "imagick-"..

```
Array
(
    [0] => /tmp/.ICE-unix
    [1] => /tmp/.Test-unix
    [2] => /tmp/.X11-unix
    [3] => /tmp/.XIM-unix
    [4] => /tmp/.font-unix
    [5] => /tmp/e3dc288df676edaaed14c5d66b43dee6/var/task/test.php.bin
    [6] => /tmp/e3dc288df676edaaed14c5d66b43dee6/var/task
    [7] => /tmp/e3dc288df676edaaed14c5d66b43dee6/var
    [8] => /tmp/e3dc288df676edaaed14c5d66b43dee6
)
```

I've also found that this change does not matter. It will give the same results.

```diff
-&& find /tmp -maxdepth 1 -type f -name "magick-*" -delete
+&& find /tmp -maxdepth 1 -type f 
```

When adding `&&` I cannot fail the job. Ie, even if an exception is thrown, we get the same result. 

If I remove all files in `/tmp/*` using PHP I still get the error. 
Hm..

**Comment by victormacko** [comment]
Ah ... ok then, that's news to me!
I'll keep digging around when time allows - not going to let it defeat us! ;)

**Comment by Nyholm** [comment]
@mnapoli do you have any good advice or recommendations for us?

**Comment by mnapoli** [comment]
Oh wow I have no idea TBH.

Might not be related, but just to be sure:

```
docker run --rm -v $$(pwd)/$${dir}:/var/task bref/test-$${dir}-$${php_version} /opt/bin/php /var/task/test.php && find /tmp -maxdepth 1 -type f -name "magick-*" -delete
```

Here I would say the `&&` makes the `find` command execute outside of Docker, is that intented?

**Comment by victormacko** [comment]
@mnapoli I'm not too familiar with Docker so am kinda learning as I go to-be-honest! ... it was intended to remove the temp-files within the docker-container - there was a reference to files not being able to get deleted all that easily which I surmised might be the problem when removing any temporary-docker-containers ... it's all just a guess though, i've never encountered something like this before.

**Comment by victormacko** [comment]
This has me puzzled & stuck -- the actual PHP side of it looks fine (I can run the docker commands individually without any issues), but not within the 'make test' context ... and I don't know enough about the internals of docker to begin debugging why it might be playing up like this, when the PHP scripts themselves can be run over & over within the docker container with no issues.
Did anyone else have any thoughts on how to debug this further, or what it could be otherwise? @Nyholm / @mnapoli / etc

**Comment by Nyholm** [comment]
Does this fix work for you? Ie in a real application without docker?

**Comment by victormacko** [comment]
Yes, after adding some missing files it's all working a'ok otherwise in staging and prod for me :)

**Comment by Nyholm** [comment]
Thank you for testing. I've disabled the extra tests. I'll merge this and prepare a release. 

Could you please double check by trying out dev-master later?

**Comment by victormacko** [comment]
Cool, no worries.
I just build the layer, exported it to my aws acct, associated it with the serverless.yaml file, tested, found a dependency (it showed which files were missing), rebuild, and try-again until they were all sorted ... not sure if there's an easier way, but it seems to have worked :)
I've downloaded dev-master, built all the layers, exported to AWS & tried -- all seems a'ok.

Hope that's all what you're after -- thanks for merging, and let me know if there's anything else you need.

**Comment by Nyholm** [comment]
Thank you

I've not deployed they layer yet. This PR will deploy things: https://github.com/brefphp/extra-php-extensions/pull/168

However, Im running into different issues. (No space on device).

**Comment by victormacko** [comment]
Np - I figured you hadn't, i'd just built the layer here, exported it to my AWS account and tested that way. No dramas RE the other PR, hopefully it's nothing too serious :)
Thanks again for your help :)

**Pull request merged**
