### PR TITLE
WIP: Add GD extension (with freetype support)

### PR DESCRIPTION
**Pull request by drAlberT**

### CODE REVIEW

**Comment by drAlberT** [comment]
@mnapoli this could be an alternative if and when the GD support compiled in PHP would be "shared", non static ..

Of course this PR is otherwiese a non-sense, not being possible to load the share object if the static one is altready loaded :)

The root issue is the lack of freetype support in GD .. if you have a different solution please apply it :)

**Comment by tomhatzer** [comment]
I wrongfully compiled this one here before doing the things from the webp PR that I should have compiled.

Anyway, as size is an important part, here's the size of the compiled changes:

```
▶ ls -alh
total 381472
drwxr-xr-x  13 tom  staff   416B 14 Jun 12:32 .
drwxr-xr-x   9 tom  staff   288B 14 Jun 11:49 ..
-rw-r--r--   1 tom  staff   1,7M 14 Jun 12:32 php-72-gd.zip
-rw-r--r--   1 tom  staff   1,7M 14 Jun 12:32 php-73-gd.zip
-rw-r--r--   1 tom  staff   1,8M 14 Jun 12:32 php-74-gd.zip
```

**Comment by shouze** [comment]
@drAlberT looks like gd will be dropped soon in 1.0 Bref base layer, see https://github.com/brefphp/bref/pull/754.

So... I'm eager to see your PR merged! How can I help? I probably have some time this week so just tell me :angel:

**Comment by drAlberT** [comment]
@shouze we have to find a way to test it on a gd-free Bref branch to assure we are not missing something

**Comment by shouze** [comment]
> @shouze we have to find a way to test it on a gd-free Bref branch to assure we are not missing something

Will do it by the end of the week for sure!

[I've documented in this issue a way to compose docker images](https://github.com/brefphp/extra-php-extensions/pull/75#issue-490427606) to obtain a resulting image on which I'll be able to test that. 

@drAlberT So I will try to at least generate and image with gd... but as your PR purpose is also to add freetype I guess that my test will be more effective if I try to add some text with a given font on this image, right? Do you have some interesting code snippet that is doing that? If yes I will be pleased to use it :smiley:

**Comment by shouze** [comment]
@drAlberT ok I've found a code snippet that I've tested on the resulting layer I've produced:
```php
<?php
$jpg_image = imagecreatefromjpeg('sunset.jpeg');
$white = imagecolorallocate($jpg_image, 255, 255, 255);
$font_path = 'Bely Display.ttf';
$text = "This is a sunset!";
imagettftext($jpg_image, 25, 0, 75, 300, $white, $font_path, $text);
imagejpeg($jpg_image, './sunset_with_legend.jpeg');
imagedestroy($jpg_image);
```

Seems to work as expected :tada: 

### Original Image

sunset


### Transformed image

sunset_with_legend

**Comment by shouze** [comment]
Used docker image to run the snippet has been built like that:
```Dockerfile
FROM bref/php-74
  
COPY --from=bref/layers/gd-php-74 /opt /opt
```

**Comment by drAlberT** [comment]
Great!

**Comment by shouze** [comment]
@drAlberT are you ok to close this PR? I've opened #76 which is your commit amended on rebased master with little missing parts.

**Comment by drAlberT** [comment]
Yep, good job @shouze thanks

**Pull request closed without merging**
