### PR TITLE
Update Imagemagick to version 7 & fix png and jpeg support

### LINKED ISSUE #104: Imagick extension stopped working
Couple of days ago imagick extension I've used stopped working. I thought it was connected to #99 but apparently it's not.

I've made very simple bref app to demonstrate it.
https://github.com/chekalsky/bref-imagick-issue

image

Error:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bref-extra/imagick.so' (tried: /opt/bref-extra/imagick.so (libgomp.so.1: cannot open shared object file: No such file or directory), /opt/bref/lib/php/extensions/no-debug-non-zts-20190902//opt/bref-extra/imagick.so.so (/opt/bref/lib/php/extensions/no-debug-non-zts-20190902//opt/bref-extra/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

### PR DESCRIPTION
**Pull request by chekalsky**
Added test for png, jpeg, gif and webp support.

This will fix #104

### CODE REVIEW

**Comment by Nyholm** [comment]
Awesome. You are the best!

Do you want to look at the Dockerfile to fix this or should I take over this PR?

**Comment by chekalsky** [comment]
@Nyholm let me try one thing...

**Comment by chekalsky** [comment]
@Nyholm it worked! 🎉 Waiting for your review.

I've also updated ImageMagick version, I didn't find any historical discussions on why's there ImageMagick6 instead of 7th version, so I just updated it. Only 7th version is actively maintained now. I can move it to different PR if you'd like.

**Review by Nyholm — APPROVED** [review]
Thank you. 

This will make sure that we never break imagick again

**Comment by mnapoli** [comment]
Awesome!

**Pull request merged**
