### PR TITLE
Add grpc extension

### LINKED ISSUE #43: gRPC Extension
I need gRPC Extension. Installation procedure is descibed [here](https://cloud.google.com/php/grpc).

### PR DESCRIPTION
**Pull request by pfazzi**
Resolve #43

### CODE REVIEW

**Comment by pfazzi** [comment]
Hi @Nyholm, could you review this PR please?

**Comment by Nyholm** [comment]
Just add your extension to the travis file and this will be okey

**Comment by pfazzi** [comment]
Do you mean the `.travis.yml` file?

**Comment by Nyholm** [comment]
Yes sir

**Comment by Nyholm** [comment]
Oh, sorry. I missed that you added that in my initial review

**Comment by Nyholm** [comment]
I'll merge when Travis is green

**Comment by pfazzi** [comment]
No prob, I just added 7.2 and 7.3 versions 😉

**Comment by Nyholm** [comment]
I did some minor changes. 

Thank you for this.

**Pull request merged**
